_extends: .template-nuget

repository:
  #─────────────────────────────────────────────────────────────────────────────
  # "About" section (on Home Page)
  # https://github.com/repository-settings/app/blob/master/docs/plugins/repository.md
  # https://docs.github.com/en/rest/repos/repos#update-a-repository
  #─────────────────────────────────────────────────────────────────────────────

  # A short description of the repo
  # MUST BE A SINGLE LINE
  description: Testing for Codecov

  # A URL with more information about the repo
  homepage:

  # A comma-separated list of topics to set on the repo
  # See https://github.com/topics
  topics: dotnet, csharp, nuget

  #─────────────────────────────────────────────────────────────────────────────
  # Settings → General
  # https://github.com/repository-settings/app/blob/master/docs/plugins/repository.md
  # https://docs.github.com/en/rest/repos/repos#update-a-repository
  #─────────────────────────────────────────────────────────────────────────────

  # The name of the repo
  name: test-me

  # Whether the repo is available as a template
  is_template: false

  # Whether to allow merging pull requests with a merge commit
  allow_merge_commit: true

  # Whether to allow rebase-merging pull requests
  allow_rebase_merge: false
